# Config file for automatic testing at circleci.com

version: 2

jobs:
  py27_tests:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest tests.test_pokepy

  py36_tests:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev27.txt --user
      - run:
          name: Run Tests
          command: python -m unittest tests.test_pokepy

  py37_tests:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: pip install -r requirements.txt -r requirements-dev.txt -r requirements-dev27.txt --user
      - run:
          name: Lint
          command: python -m pylint pokepy tests setup.py
      - run:
          name: Run Tests
          command: python -m unittest tests.test_pokepy
      - run:
          name: Run Coverage tool
          command: coverage run --source pokepy setup.py test
      - run:
          name: Generate XML coverage report
          command: coverage xml
      - run:
          name: Upload Coverage report to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  run_tests:
    jobs:
      - py27_tests
      - py36_tests
      - py37_tests